services:

  ollama:
    build:
      context: ../ollama  # Path to the Ollama Dockerfile
      dockerfile: Dockerfile
    ports:
      - 11434:11434
    volumes:
      - ollama-vol:/ollama  # Volume to persist Ollama models
    networks:
      - chatbot-net
    entrypoint: ["/usr/bin/bash", "pull-llama3.sh"]

  selenium:
  build:
    context: ../selenium  # Path to the Ollama Dockerfile
    dockerfile: Dockerfile
  ports:
    - 123:123

networks:
  chatbot-net:
    driver: bridge

volumes:
  ollama-vol:
    driver: local
